# Generated by Django 3.2.8 on 2022-06-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='リリース日')),
                ('title', models.CharField(max_length=32, unique=True, verbose_name='リリース概要')),
                ('description', models.TextField(max_length=400, verbose_name='リリース内容')),
            ],
            options={
                'verbose_name': 'リリース履歴',
                'verbose_name_plural': 'リリース履歴',
            },
        ),
    ]
