# Generated by Django 3.2.8 on 2022-06-04 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_gacha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunchplace',
            name='has_eatin',
            field=models.BooleanField(default=False, verbose_name='店内飲食'),
        ),
        migrations.AddField(
            model_name='lunchplace',
            name='has_takeout',
            field=models.BooleanField(default=False, verbose_name='持ち帰り'),
        ),
    ]
