# Generated by Django 3.2.8 on 2022-06-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_gacha', '0003_auto_20220604_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='storetype',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='説明'),
        ),
    ]
