# Generated by Django 3.2.8 on 2022-06-04 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_gacha', '0004_storetype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunchplace',
            name='store_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lunch_gacha.storetype', verbose_name='店舗形態'),
        ),
    ]
